import { getPriceConversion } from "./getPriceConversion";

export const plans = [
  {
    name: "Silver Plan",
    period: "weekly",
    price: "599",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO2VxrDawWH",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
      "1 live session per week",
      "1 recorded revision session per week",
      "2 hours live support / day",
    ],
    star: [],
    superStar: [],
    _id: "d8cc4ea7-80a-a8ce-dc839bce88b1",
  },
  {
    name: "Silver Plan",
    period: "monthly",
    price: "2299",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO22YjXN0Qs",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
      "1 live session per week",
      "1 recorded revision session per week",
      "2 hours live support / day",
    ],
    star: [],
    superStar: [],
    _id: "d8cc4ea7-8092-480a-a8839bce88b1",
  },
  {
    name: "Golden Plan",
    period: "weekly",
    price: "699",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO2iucJbhOj",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
    ],
    star: [
      "2 live session per week",
      "2 recorded revision session per week",
      "4 hours live support / day",
    ],
    superStar: [
      "One to one live lecture with tutor",
      "1 : 1 career support (CV & portfolio guidance) (Github account review & support)(LinkedIn account review & support)",
    ],
    _id: "d8cc4ea7-809a-a8ce-dc839bce88b1",
  },
  {
    name: "Golden Plan",
    period: "monthly",
    price: "2699",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO2CeL53NQp",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
    ],
    star: [
      "2 live session per week",
      "2 recorded revision session per week",
      "4 hours live support / day",
    ],
    superStar: [
      "One to one live lecture with tutor",
      "1 : 1 career support (CV & portfolio guidance) (Github account review & support)(LinkedIn account review & support)",
    ],
    _id: "d8cc4e92-480a-a8ce-dc839bce88b1",
  },
  {
    name: "Diamond Plan",
    period: "weekly",
    price: "899",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO2tRzUCERv",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
    ],
    star: [
      "3 live session per week",
      "2 recorded revision session per week",
      "6 hours live support / day",
      "One to one live lecture with tutor",
      "1 : 1 career support (CV & portfolio guidance) (Github account review & support)(LinkedIn account review & support)",
    ],
    superStar: [
      "Hiring interview simulation",
      "Access to global hiring partner network",
    ],
    _id: "4ea7-8092-480a-a8ce-dc839bce88b1",
  },
  {
    name: "Diamond Plan",
    period: "monthly",
    price: "3499",
    stripeSubscriptionId: "price_1JQUF8BDalVdaGO2vI1gRfC3",
    basic: [
      "Free foundation course",
      "Industry Curriculun (IC)",
      "In-trend online learning platform",
      "Remote learning - no compromise on your job",
      "Hands on experience on real-world problems",
      "Flexible payment plans",
      "Maximum purchase - 4 weeks",
    ],
    star: [
      "3 live session per week",
      "2 recorded revision session per week",
      "6 hours live support / day",
      "One to one live lecture with tutor",
      "1 : 1 career support (CV & portfolio guidance) (Github account review & support)(LinkedIn account review & support)",
    ],
    superStar: [
      "Hiring interview simulation",
      "Access to global hiring partner network",
    ],
    _id: "d8cc4ea7-8092-480a-a8ce-dc888b1",
  },
];
