export const APPOINTMENT_ADD_REQUEST = 'APPOINTMENT_ADD_REQUEST'
export const APPOINTMENT_ADD_SUCCESS = 'APPOINTMENT_ADD_SUCCESS'
export const APPOINTMENT_ADD_FAIL = 'APPOINTMENT_ADD_FAIL'

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST'
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS'
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL'

export const INSTRUCTOR_APPOINTMENT_LIST_REQUEST = 'INSTRUCTOR_APPOINTMENT_LIST_REQUEST'
export const INSTRUCTOR_APPOINTMENT_LIST_SUCCESS = 'INSTRUCTOR_APPOINTMENT_LIST_SUCCESS'
export const INSTRUCTOR_APPOINTMENT_LIST_FAIL = 'INSTRUCTOR_APPOINTMENT_LIST_FAIL'

export const APPOINTMENT_DETAILS_REQUEST = 'APPOINTMENT_DETAILS_REQUEST'
export const APPOINTMENT_DETAILS_SUCCESS = 'APPOINTMENT_DETAILS_SUCCESS'
export const APPOINTMENT_DETAILS_FAIL = 'APPOINTMENT_DETAILS_FAIL'

export const APPOINTMENT_DELETE_REQUEST = "APPOINTMENT_DELETE_REQUEST";
export const APPOINTMENT_DELETE_SUCCESS = "APPOINTMENT_DELETE_SUCCESS";
export const APPOINTMENT_DELETE_FAIL = "APPOINTMENT_DELETE_FAIL";

export const APPOINTMENT_UPDATE_REQUEST = "APPOINTMENT_UPDATE_REQUEST";
export const APPOINTMENT_UPDATE_SUCCESS = "APPOINTMENT_UPDATE_SUCCESS";
export const APPOINTMENT_UPDATE_FAIL = "APPOINTMENT_UPDATE_FAIL";
