export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'

export const ORDER_KLARNA_CREATE_REQUEST = 'ORDER_KLARNA_CREATE_REQUEST'
export const ORDER_KLARNA_CREATE_SUCCESS = 'ORDER_KLARNA_CREATE_SUCCESS'
export const ORDER_KLARNA_CREATE_FAIL = 'ORDER_KLARNA_CREATE_FAIL'


export const ORDER_KLARNA_READ_REQUEST = 'ORDER_KLARNA_READ_REQUEST'
export const ORDER_KLARNA_READ_SUCCESS = 'ORDER_KLARNA_READ_SUCCESS'
export const ORDER_KLARNA_READ_FAIL = 'ORDER_KLARNA_READ_FAIL'