export const PERFORMANCE_ADD_REQUEST = 'PERFORMANCE_ADD_REQUEST'
export const PERFORMANCE_ADD_SUCCESS = 'PERFORMANCE_ADD_SUCCESS'
export const PERFORMANCE_ADD_FAIL = 'PERFORMANCE_ADD_FAIL'

export const PERFORMANCE_LIST_REQUEST = 'PERFORMANCE_LIST_REQUEST'
export const PERFORMANCE_LIST_SUCCESS = 'PERFORMANCE_LIST_SUCCESS'
export const PERFORMANCE_LIST_FAIL = 'PERFORMANCE_LIST_FAIL'

export const PERFORMANCE_LECTURE_LIST_REQUEST = 'PERFORMANCE_LECTURE_LIST_REQUEST'
export const PERFORMANCE_LECTURE_LIST_SUCCESS = 'PERFORMANCE_LECTURE_LIST_SUCCESS'
export const PERFORMANCE_LECTURE_LIST_FAIL = 'PERFORMANCE_LECTURE_LIST_FAIL'

export const PERFORMANCE_DETAILS_REQUEST = 'PERFORMANCE_DETAILS_REQUEST'
export const PERFORMANCE_DETAILS_SUCCESS = 'PERFORMANCE_DETAILS_SUCCESS'
export const PERFORMANCE_DETAILS_FAIL = 'PERFORMANCE_DETAILS_FAIL'

export const PERFORMANCE_DELETE_REQUEST = "PERFORMANCE_DELETE_REQUEST";
export const PERFORMANCE_DELETE_SUCCESS = "PERFORMANCE_DELETE_SUCCESS";
export const PERFORMANCE_DELETE_FAIL = "PERFORMANCE_DELETE_FAIL";

export const PERFORMANCE_UPDATE_REQUEST = "PERFORMANCE_UPDATE_REQUEST";
export const PERFORMANCE_UPDATE_SUCCESS = "PERFORMANCE_UPDATE_SUCCESS";
export const PERFORMANCE_UPDATE_FAIL = "PERFORMANCE_UPDATE_FAIL";

export const TOP_PERFORMANCE_LIST_REQUEST = 'TOP_PERFORMANCE_LIST_REQUEST'
export const TOP_PERFORMANCE_LIST_SUCCESS = 'TOP_PERFORMANCE_LIST_SUCCESS'
export const TOP_PERFORMANCE_LIST_FAIL = 'TOP_PERFORMANCE_LIST_FAIL'
