export const PROMO_ADD_REQUEST = 'PROMO_ADD_REQUEST'
export const PROMO_ADD_SUCCESS = 'PROMO_ADD_SUCCESS'
export const PROMO_ADD_FAIL = 'PROMO_ADD_FAIL'

export const PROMO_LIST_REQUEST = 'PROMO_LIST_REQUEST'
export const PROMO_LIST_SUCCESS = 'PROMO_LIST_SUCCESS'
export const PROMO_LIST_FAIL = 'PROMO_LIST_FAIL'

export const PROMO_DETAILS_REQUEST = 'PROMO_DETAILS_REQUEST'
export const PROMO_DETAILS_SUCCESS = 'PROMO_DETAILS_SUCCESS'
export const PROMO_DETAILS_FAIL = 'PROMO_DETAILS_FAIL'

export const PROMO_DELETE_REQUEST = "PROMO_DELETE_REQUEST";
export const PROMO_DELETE_SUCCESS = "PROMO_DELETE_SUCCESS";
export const PROMO_DELETE_FAIL = "PROMO_DELETE_FAIL";

export const PROMO_UPDATE_REQUEST = "PROMO_UPDATE_REQUEST";
export const PROMO_UPDATE_SUCCESS = "PROMO_UPDATE_SUCCESS";
export const PROMO_UPDATE_FAIL = "PROMO_UPDATE_FAIL";
