export const REQUEST_ADD_REQUEST = 'REQUEST_ADD_REQUEST'
export const REQUEST_ADD_SUCCESS = 'REQUEST_ADD_SUCCESS'
export const REQUEST_ADD_FAIL = 'REQUEST_ADD_FAIL'

export const REQUEST_LIST_REQUEST = 'REQUEST_LIST_REQUEST'
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS'
export const REQUEST_LIST_FAIL = 'REQUEST_LIST_FAIL'

export const REQUEST_DETAILS_REQUEST = 'REQUEST_DETAILS_REQUEST'
export const REQUEST_DETAILS_SUCCESS = 'REQUEST_DETAILS_SUCCESS'
export const REQUEST_DETAILS_FAIL = 'REQUEST_DETAILS_FAIL'

export const REQUEST_DELETE_REQUEST = "REQUEST_DELETE_REQUEST";
export const REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";
export const REQUEST_DELETE_FAIL = "REQUEST_DELETE_FAIL";

export const REQUEST_UPDATE_REQUEST = "REQUEST_UPDATE_REQUEST";
export const REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
export const REQUEST_UPDATE_FAIL = "REQUEST_UPDATE_FAIL";
