export const REQUEST_ADD_REQUEST = 'REQUEST_ADD_REQUEST'
export const REQUEST_ADD_SUCCESS = 'REQUEST_ADD_SUCCESS'
export const REQUEST_ADD_FAIL = 'REQUEST_ADD_FAIL'

export const REQUEST_LIST_REQUEST = 'REQUEST_LIST_REQUEST'
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS'
export const REQUEST_LIST_FAIL = 'REQUEST_LIST_FAIL'
