export const SERVICE_CATEGORY_ADD_REQUEST = 'SERVICE_CATEGORY_ADD_REQUEST'
export const SERVICE_CATEGORY_ADD_SUCCESS = 'SERVICE_CATEGORY_ADD_SUCCESS'
export const SERVICE_CATEGORY_ADD_FAIL = 'SERVICE_CATEGORY_ADD_FAIL'

export const SERVICE_CATEGORY_LIST_REQUEST = 'SERVICE_CATEGORY_LIST_REQUEST'
export const SERVICE_CATEGORY_LIST_SUCCESS = 'SERVICE_CATEGORY_LIST_SUCCESS'
export const SERVICE_CATEGORY_LIST_FAIL = 'SERVICE_CATEGORY_LIST_FAIL'

export const SERVICE_CATEGORY_DETAILS_REQUEST = 'SERVICE_CATEGORY_DETAILS_REQUEST'
export const SERVICE_CATEGORY_DETAILS_SUCCESS = 'SERVICE_CATEGORY_DETAILS_SUCCESS'
export const SERVICE_CATEGORY_DETAILS_FAIL = 'SERVICE_CATEGORY_DETAILS_FAIL'

export const SERVICE_CATEGORY_DELETE_REQUEST = "SERVICE_CATEGORY_DELETE_REQUEST";
export const SERVICE_CATEGORY_DELETE_SUCCESS = "SERVICE_CATEGORY_DELETE_SUCCESS";
export const SERVICE_CATEGORY_DELETE_FAIL = "SERVICE_CATEGORY_DELETE_FAIL";

export const SERVICE_CATEGORY_UPDATE_REQUEST = "SERVICE_CATEGORY_UPDATE_REQUEST";
export const SERVICE_CATEGORY_UPDATE_SUCCESS = "SERVICE_CATEGORY_UPDATE_SUCCESS";
export const SERVICE_CATEGORY_UPDATE_FAIL = "SERVICE_CATEGORY_UPDATE_FAIL";
