export const SESSION_ADD_REQUEST = 'SESSION_ADD_REQUEST'
export const SESSION_ADD_SUCCESS = 'SESSION_ADD_SUCCESS'
export const SESSION_ADD_FAIL = 'SESSION_ADD_FAIL'

export const SESSION_LIST_REQUEST = 'SESSION_LIST_REQUEST'
export const SESSION_LIST_SUCCESS = 'SESSION_LIST_SUCCESS'
export const SESSION_LIST_FAIL = 'SESSION_LIST_FAIL'

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST'
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS'
export const SESSION_DETAILS_FAIL = 'SESSION_DETAILS_FAIL'

export const SESSION_DELETE_REQUEST = "SESSION_DELETE_REQUEST";
export const SESSION_DELETE_SUCCESS = "SESSION_DELETE_SUCCESS";
export const SESSION_DELETE_FAIL = "SESSION_DELETE_FAIL";

export const SESSION_UPDATE_REQUEST = "SESSION_UPDATE_REQUEST";
export const SESSION_UPDATE_SUCCESS = "SESSION_UPDATE_SUCCESS";
export const SESSION_UPDATE_FAIL = "SESSION_UPDATE_FAIL";
